version: "3.7"

services:
  web:
    image: image_name
    env_file:
      - ./.env.dev
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --no-input &&
             gunicorn project_api.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - static_volume:/home/app/static/
    environment:
      - TZ=Asia/Seoul
    expose:
      - 8000
  nginx:
    image: image_name
    volumes:
      - static_volume:/home/app/static/
    environment:
      - TZ=Asia/Seoul
    ports:
      - 80
    depends_on:
      - web
volumes:
  static_volume:
