# Generated by Django 3.2.12 on 2022-11-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExerciseDetailRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="운동 시작 시간")),
                ("duration", models.IntegerField(verbose_name="지속 시간(초)")),
                ("distance", models.FloatField(verbose_name="이동한 거리")),
                ("heart_rate", models.IntegerField(verbose_name="심장 박동수")),
                ("altitude", models.FloatField(verbose_name="고도")),
                ("latitude", models.FloatField(verbose_name="위도")),
                ("longitude", models.FloatField(verbose_name="경도")),
                ("speed", models.FloatField(verbose_name="속도")),
            ],
        ),
        migrations.CreateModel(
            name="ExerciseRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="운동 날짜")),
                ("distance", models.FloatField(verbose_name="운동 거리")),
                ("time", models.TimeField(verbose_name="운동 시간")),
                ("average_speed", models.FloatField(verbose_name="운동 평균 속도")),
                ("calories", models.FloatField(verbose_name="운동 칼로리")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
