# Generated by Django 3.2.12 on 2022-12-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exerciserecord",
            old_name="calories",
            new_name="total_calories",
        ),
        migrations.RenameField(
            model_name="exerciserecord",
            old_name="distance",
            new_name="total_distance",
        ),
        migrations.RenameField(
            model_name="exerciserecord",
            old_name="time",
            new_name="total_time",
        ),
        migrations.RemoveField(
            model_name="exerciserecord",
            name="date",
        ),
        migrations.AddField(
            model_name="exerciserecord",
            name="start_datetime",
            field=models.DateTimeField(
                default="2022-12-13 13:50:03.281557+09", verbose_name="운동 날짜"
            ),
            preserve_default=False,
        ),
    ]
