# Generated by Django 3.2.12 on 2023-01-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0003_auto_20221213_1608"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercisedetailrecord",
            name="altitude",
            field=models.FloatField(null=True, verbose_name="고도"),
        ),
        migrations.AlterField(
            model_name="exercisedetailrecord",
            name="heart_rate",
            field=models.PositiveSmallIntegerField(verbose_name="심장 박동수"),
        ),
        migrations.AlterField(
            model_name="exercisedetailrecord",
            name="latitude",
            field=models.FloatField(null=True, verbose_name="위도"),
        ),
        migrations.AlterField(
            model_name="exercisedetailrecord",
            name="longitude",
            field=models.FloatField(null=True, verbose_name="경도"),
        ),
    ]
