# Generated by Django 3.2.12 on 2022-11-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginlink",
            name="type",
            field=models.CharField(
                choices=[("A", "애플"), ("G", "구글"), ("E", "이메일"), ("D", "삭제")],
                max_length=5,
                verbose_name="타입",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "남자"),
                    ("F", "여자"),
                    ("N", "선택 안함"),
                    ("D", "삭제"),
                ],
                max_length=1,
                null=True,
                verbose_name="성별",
            ),
        ),
        migrations.AddConstraint(
            model_name="loginlink",
            constraint=models.UniqueConstraint(
                fields=("type", "link_email"), name="unique_link_email_type"
            ),
        ),
    ]
