# Generated by Django 3.2.12 on 2022-11-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_auto_20221125_1600"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RemoveConstraint(
            model_name="loginlink",
            name="unique_link_email_type",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="unique_username",
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                unique=True,
                verbose_name="유저명(닉네임)",
            ),
        ),
        migrations.AddConstraint(
            model_name="loginlink",
            constraint=models.UniqueConstraint(
                fields=("type", "link_email"), name="unique_link_email"
            ),
        ),
    ]
