# Generated by Django 3.2.12 on 2022-11-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_auto_20221125_1638"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginlink",
            name="link_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="링크 이메일"
            ),
        ),
    ]
