# Generated by Django 3.2.12 on 2022-11-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_loginlink_link_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="app_push",
            field=models.BooleanField(default=True, verbose_name="앱푸시 온오프"),
        ),
    ]
