# Generated by Django 3.2.12 on 2022-12-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_auto_20221130_1002"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("IOS", "아이폰"),
                    ("AOS", "안드로이드"),
                    ("ETC", "기타"),
                    ("D", "삭제"),
                ],
                default="AOS",
                max_length=5,
                verbose_name="디바이스 타입",
            ),
            preserve_default=False,
        ),
    ]
