# Generated by Django 3.2.12 on 2022-12-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_device_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="device_type",
            field=models.CharField(
                choices=[("ios", "IOS"), ("aos", "Android")],
                max_length=5,
                verbose_name="디바이스 타입",
            ),
        ),
    ]
