# Generated by Django 3.2.12 on 2023-01-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_userprofileuploadedimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="height",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="키"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="weight",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="몸무게"
            ),
        ),
    ]
