# Generated by Django 3.2.12 on 2023-01-17 15:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_phoneverification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="phoneverification",
            old_name="phone",
            new_name="phone_number",
        ),
    ]
