# Generated by Django 3.2.12 on 2023-01-18 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_phoneverification_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneverification",
            name="user",
            field=models.ForeignKey(
                default=44,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.user",
                verbose_name="유저",
            ),
            preserve_default=False,
        ),
    ]
