# Generated by Django 3.2.12 on 2022-12-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("commons", "0002_uploadedimage_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appversion",
            name="device_type",
            field=models.CharField(
                choices=[("aos", "Android"), ("ios", "IOS")],
                max_length=3,
                verbose_name="기기 OS 타입",
            ),
        ),
    ]
