"""
Django settings for project_api project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
import socket
import sys
from pathlib import Path

import firebase_admin

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(os.environ.get("DEBUG", default=0))

# ALLOWED_HOSTS
ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS")

# Django App들을 apps directory에 모아서 처리하기위해 아래 system path를 추가해줌
sys.path.insert(0, os.path.join(BASE_DIR, "project_api/apps"))

# Django 3.2 버전부터 Primary Key 속성을 설정해줘야하는 것 때문에 나오는 Warning을 해결하기 위한 코드
DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

cred_obj = firebase_admin.credentials.Certificate("./FBserviceAccountKey.json")

default_app = firebase_admin.initialize_app(cred_obj)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # Packages installed by pip (3rd party apps)
    "rest_framework",
    "rest_framework.authtoken",
    "dj_rest_auth",
    "drf_yasg",
    "firebase_admin",
    # Custom Apps
    "commons",
    "users",
    "exercises",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.gzip.GZipMiddleware",
]

ROOT_URLCONF = "project_api.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project_api.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("DB_ENGINE"),
        "NAME": os.environ.get("DB_NAME"),
        "USER": os.environ.get("DB_USER"),
        "PASSWORD": os.environ.get("DB_PASSWORD"),
        "HOST": os.environ.get("DB_HOST"),
        "PORT": os.environ.get("DB_PORT"),
    },
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "project_api.custom_password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "project_api.custom_password_validation.CommonPasswordValidator",
    },
    {"NAME": "project_api.custom_password_validation.NumberEnglishMixPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/
LANGUAGE_CODE = "ko"

LANGUAGES = [
    ("ko", _("Korean")),
    ("en", _("English")),
]


LOCALE_PATHS = (os.path.join(BASE_DIR, "locale"),)

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_L10N = True
# 한국(서울) 기준 시간을 사용하기 위해 False처리
# 이 경우 해당 프로젝트는 docker container의 시간을 따른다.
USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")


# Django Rest Framework Settings
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly"
    ],
    # 하단 옵션은 Dev 모드일 때에는 주석처리
    # 'DEFAULT_RENDERER_CLASSES': (
    #     'rest_framework.renderers.JSONRenderer',
    # ),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework.authentication.TokenAuthentication",
        # 'rest_framework.authentication.SessionAuthentication',
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 12,
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.coreapi.AutoSchema",
    "EXCEPTION_HANDLER": "project_api.custom_exception_handler.custom_exception_handler",
}

AUTH_USER_MODEL = "users.User"

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of allauth
    "django.contrib.auth.backends.ModelBackend",
]


SITE_ID = 1

ACCOUNT_AUTHENTICATION_METHOD = "user_code"
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = "none"

SWAGGER_SETTINGS = {
    "DEFAULT_AUTO_SCHEMA_CLASS": "project_api.utils.ReadWriteAutoSchema",
    "SECURITY_DEFINITIONS": {
        "api_key": {"type": "apiKey", "in": "header", "name": "Authorization"}
    },
    "JSON_EDITOR": True,
}


# *** AWS Configuration ****
AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
AWS_REGION = os.environ.get("AWS_REGION")

# django-storages to S3 ---------------
AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
AWS_S3_CUSTOM_DOMAIN = "%s.s3.%s.amazonaws.com" % (
    AWS_STORAGE_BUCKET_NAME,
    AWS_REGION,
)
AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": "max-age=86400",
}
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
AWS_S3_CUSTOM_DOMAIN = "d1dzkb91qond6a.cloudfront.net"
# -------------------------------------

# django-cors-headers Options ---------
ALLOWED_HOSTS = ["*"]
CORS_ORIGIN_ALLOW_ALL = True
# -------------------------------------


DDT = "DDT"
SILK = "SILK"
USING_TOOL_SELECTION = {
    0: None,
    1: DDT,
    2: SILK,
}
USING_TOOL = USING_TOOL_SELECTION[0]
if DEBUG:
    if USING_TOOL == DDT:
        # django-debug-toolbar 활성화 및 설정
        INSTALLED_APPS += ["debug_toolbar"]
        MIDDLEWARE += ["debug_toolbar.middleware.DebugToolbarMiddleware"]
        hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
        INTERNAL_IPS = [ip[:-1] + "1" for ip in ips] + [
            "127.0.0.1",
            "10.0.2.2",
        ]
        DEBUG_TOOLBAR_PANELS = [
            "debug_toolbar.panels.versions.VersionsPanel",
            "debug_toolbar.panels.timer.TimerPanel",
            "debug_toolbar.panels.settings.SettingsPanel",
            "debug_toolbar.panels.headers.HeadersPanel",
            "debug_toolbar.panels.request.RequestPanel",
            "debug_toolbar.panels.sql.SQLPanel",
            "debug_toolbar.panels.templates.TemplatesPanel",
            "debug_toolbar.panels.staticfiles.StaticFilesPanel",
            "debug_toolbar.panels.cache.CachePanel",
            "debug_toolbar.panels.signals.SignalsPanel",
            "debug_toolbar.panels.logging.LoggingPanel",
            "debug_toolbar.panels.redirects.RedirectsPanel",
            "debug_toolbar.panels.profiling.ProfilingPanel",
        ]
        DEBUG_TOOLBAR_CONFIG = {
            "RESULTS_STORE_SIZE": 100,
        }

    if USING_TOOL == SILK:
        # 사용시에만 INSTALLED_APPS 에 추가하여 사용
        INSTALLED_APPS += ["silk"]
        # silk 미들웨어 추가하여 활성화
        MIDDLEWARE += ["silk.middleware.SilkyMiddleware"]
        # silk configuration
        # SILKY_AUTHENTICATION = True
        # SILKY_AUTHORISATION = True
        SILKY_PYTHON_PROFILER = True

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "email-smtp.ap-northeast-2.amazonaws.com"
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get("SES_SMTP_ID")
EMAIL_HOST_PASSWORD = os.environ.get("SES_SMTP_PW")
DEFAULT_FROM_EMAIL = "info@popprika.com"
SERVER_EMAIL = "las@popprika.com"
ADMINS = [("ethan", "ethan@popprika.com"), ("las", "las@popprika.com")]


FIREBASE_APP = default_app
